// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241121020321_Importers_4")]
    partial class Importers_4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-rc.1.24451.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("ACompanySequence");

            modelBuilder.HasSequence("AHomeSequence");

            modelBuilder.HasSequence("ANotificationSequence");

            modelBuilder.HasSequence("ARoomSequence");

            modelBuilder.HasSequence("AUserSequence");

            modelBuilder.HasSequence("AUserTypeSequence");

            modelBuilder.Entity("ModelInterface.Companys.ACompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [ACompanySequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<int>("CompanyOwnerId")
                        .HasColumnType("int");

                    b.Property<string>("LogoType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidationType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyOwnerId")
                        .IsUnique();

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ModelInterface.Devices.ADevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeviceType")
                        .HasColumnType("int");

                    b.Property<string>("MainPhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Devices", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ModelInterface.Devices.AHomeDevice", b =>
                {
                    b.Property<Guid>("HardwareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("HomeId")
                        .HasColumnType("int");

                    b.Property<int?>("LastEvent")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Online")
                        .HasColumnType("bit");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("HardwareId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("HomeId");

                    b.HasIndex("RoomId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ModelInterface.Devices.DevicePhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("DevicePhoto");
                });

            modelBuilder.Entity("ModelInterface.Homes.AHome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [AHomeSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<int>("DoorNumber")
                        .HasColumnType("int");

                    b.Property<int>("HomeOwnerId")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("MainStreet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HomeOwnerId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ModelInterface.Homes.ARoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [ARoomSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<int>("HomeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ModelInterface.Notifications.ANotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [ANotificationSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<int?>("AHomeMemberHomeId")
                        .HasColumnType("int");

                    b.Property<int?>("AHomeMemberUserId")
                        .HasColumnType("int");

                    b.Property<int?>("AHomeUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeviceHardwareId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Event")
                        .HasColumnType("int");

                    b.Property<bool>("Read")
                        .HasColumnType("bit");

                    b.Property<int>("UserHomeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AHomeUserId");

                    b.HasIndex("DeviceHardwareId");

                    b.HasIndex("AHomeMemberHomeId", "AHomeMemberUserId");

                    b.HasIndex("UserHomeId", "UserId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ModelInterface.Users.AHomeMember", b =>
                {
                    b.Property<int>("HomeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("AddDevices")
                        .HasColumnType("bit");

                    b.Property<bool>("ListDevices")
                        .HasColumnType("bit");

                    b.Property<bool>("Notifiable")
                        .HasColumnType("bit");

                    b.Property<bool>("UpdateDevices")
                        .HasColumnType("bit");

                    b.HasKey("HomeId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ModelInterface.Users.AUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [AUserSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ModelInterface.Users.UserType.AUserType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [AUserTypeSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Models.Sessions.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Token")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("Models.Company.Company", b =>
                {
                    b.HasBaseType("ModelInterface.Companys.ACompany");

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("Models.Devices.Camera", b =>
                {
                    b.HasBaseType("ModelInterface.Devices.ADevice");

                    b.Property<bool>("MovementDetection")
                        .HasColumnType("bit");

                    b.Property<bool>("OutsideEnvironment")
                        .HasColumnType("bit");

                    b.Property<bool>("PersonDetection")
                        .HasColumnType("bit");

                    b.ToTable("Cameras", (string)null);
                });

            modelBuilder.Entity("Models.Devices.MotionSensor", b =>
                {
                    b.HasBaseType("ModelInterface.Devices.ADevice");

                    b.ToTable("MotionSensors", (string)null);
                });

            modelBuilder.Entity("Models.Devices.Sensor", b =>
                {
                    b.HasBaseType("ModelInterface.Devices.ADevice");

                    b.ToTable("Sensors", (string)null);
                });

            modelBuilder.Entity("Models.Devices.SmartLamp", b =>
                {
                    b.HasBaseType("ModelInterface.Devices.ADevice");

                    b.ToTable("SmartLamps", (string)null);
                });

            modelBuilder.Entity("Models.Devices.HomeDevice", b =>
                {
                    b.HasBaseType("ModelInterface.Devices.AHomeDevice");

                    b.ToTable("HomeDevices", (string)null);
                });

            modelBuilder.Entity("Models.Homes.Home", b =>
                {
                    b.HasBaseType("ModelInterface.Homes.AHome");

                    b.ToTable("Homes", (string)null);
                });

            modelBuilder.Entity("Models.Homes.Room", b =>
                {
                    b.HasBaseType("ModelInterface.Homes.ARoom");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("Models.Notifications.Notification", b =>
                {
                    b.HasBaseType("ModelInterface.Notifications.ANotification");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("Models.Users.UserTypes.HomeMember", b =>
                {
                    b.HasBaseType("ModelInterface.Users.AHomeMember");

                    b.ToTable("HomeMembers");
                });

            modelBuilder.Entity("Models.Users.User", b =>
                {
                    b.HasBaseType("ModelInterface.Users.AUser");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ModelInterface.Users.UserType.ACompanyOwner", b =>
                {
                    b.HasBaseType("ModelInterface.Users.UserType.AUserType");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.HasIndex("CompanyId");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("ModelInterface.Users.UserType.AHomeUser", b =>
                {
                    b.HasBaseType("ModelInterface.Users.UserType.AUserType");

                    b.Property<int?>("AHomeId")
                        .HasColumnType("int");

                    b.Property<string>("ProfilePhoto")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("AHomeId");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("Models.Users.UserTypes.Admin", b =>
                {
                    b.HasBaseType("ModelInterface.Users.UserType.AUserType");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("Models.Users.UserTypes.CompanyOwner", b =>
                {
                    b.HasBaseType("ModelInterface.Users.UserType.ACompanyOwner");

                    b.ToTable("CompanyOwners", (string)null);
                });

            modelBuilder.Entity("Models.Users.UserTypes.HomeUser", b =>
                {
                    b.HasBaseType("ModelInterface.Users.UserType.AHomeUser");

                    b.ToTable("HomeUsers", (string)null);
                });

            modelBuilder.Entity("ModelInterface.Companys.ACompany", b =>
                {
                    b.HasOne("ModelInterface.Users.UserType.ACompanyOwner", "CompanyOwner")
                        .WithOne()
                        .HasForeignKey("ModelInterface.Companys.ACompany", "CompanyOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyOwner");
                });

            modelBuilder.Entity("ModelInterface.Devices.ADevice", b =>
                {
                    b.HasOne("ModelInterface.Companys.ACompany", "Company")
                        .WithMany("Devices")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ModelInterface.Devices.AHomeDevice", b =>
                {
                    b.HasOne("ModelInterface.Devices.ADevice", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModelInterface.Homes.AHome", "Home")
                        .WithMany("Devices")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelInterface.Homes.ARoom", "Room")
                        .WithMany("Devices")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Device");

                    b.Navigation("Home");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("ModelInterface.Devices.DevicePhoto", b =>
                {
                    b.HasOne("ModelInterface.Devices.ADevice", "Device")
                        .WithMany("Photos")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("ModelInterface.Homes.AHome", b =>
                {
                    b.HasOne("ModelInterface.Users.UserType.AHomeUser", "Owner")
                        .WithMany()
                        .HasForeignKey("HomeOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ModelInterface.Homes.ARoom", b =>
                {
                    b.HasOne("ModelInterface.Homes.AHome", "Home")
                        .WithMany("Rooms")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Home");
                });

            modelBuilder.Entity("ModelInterface.Notifications.ANotification", b =>
                {
                    b.HasOne("ModelInterface.Users.UserType.AHomeUser", null)
                        .WithMany("Notifications")
                        .HasForeignKey("AHomeUserId");

                    b.HasOne("ModelInterface.Devices.AHomeDevice", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceHardwareId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModelInterface.Users.AHomeMember", null)
                        .WithMany("Notifications")
                        .HasForeignKey("AHomeMemberHomeId", "AHomeMemberUserId");

                    b.HasOne("ModelInterface.Users.AHomeMember", "User")
                        .WithMany()
                        .HasForeignKey("UserHomeId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModelInterface.Users.AHomeMember", b =>
                {
                    b.HasOne("ModelInterface.Homes.AHome", "Home")
                        .WithMany("Members")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelInterface.Users.UserType.AHomeUser", "AHomeUser")
                        .WithMany("Homes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AHomeUser");

                    b.Navigation("Home");
                });

            modelBuilder.Entity("ModelInterface.Users.UserType.AUserType", b =>
                {
                    b.HasOne("ModelInterface.Users.AUser", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.Sessions.Session", b =>
                {
                    b.HasOne("ModelInterface.Users.AUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.Devices.Camera", b =>
                {
                    b.HasOne("ModelInterface.Devices.ADevice", null)
                        .WithOne()
                        .HasForeignKey("Models.Devices.Camera", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Devices.MotionSensor", b =>
                {
                    b.HasOne("ModelInterface.Devices.ADevice", null)
                        .WithOne()
                        .HasForeignKey("Models.Devices.MotionSensor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Devices.Sensor", b =>
                {
                    b.HasOne("ModelInterface.Devices.ADevice", null)
                        .WithOne()
                        .HasForeignKey("Models.Devices.Sensor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Devices.SmartLamp", b =>
                {
                    b.HasOne("ModelInterface.Devices.ADevice", null)
                        .WithOne()
                        .HasForeignKey("Models.Devices.SmartLamp", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModelInterface.Users.UserType.ACompanyOwner", b =>
                {
                    b.HasOne("ModelInterface.Companys.ACompany", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ModelInterface.Users.UserType.AHomeUser", b =>
                {
                    b.HasOne("ModelInterface.Homes.AHome", null)
                        .WithMany("Users")
                        .HasForeignKey("AHomeId");
                });

            modelBuilder.Entity("ModelInterface.Companys.ACompany", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("ModelInterface.Devices.ADevice", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("ModelInterface.Homes.AHome", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Members");

                    b.Navigation("Rooms");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ModelInterface.Homes.ARoom", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("ModelInterface.Users.AHomeMember", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("ModelInterface.Users.AUser", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("ModelInterface.Users.UserType.AHomeUser", b =>
                {
                    b.Navigation("Homes");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
